### ISSUE TITLE
Finish homework

### ISSUE THREAD

**Issue by Qwebeck** [Artinov/home-work-9-Qwebeck#1]

**Comment by eko24ive** [comment]
I really loved this approach that you've commented out:
```js
// setInterval(goToDisco,600)
// setInterval(goOur,900)
// setInterval(awesome,1200)
// setInterval(disco,1500)
// setInterval(finishDisco,1800);
```

Which eventually shows that you really put effort in this work, and even further - you've refactored your code into single call of `setInterval` with is super awesome !
Consider taking a look at #2 which is the only issue I've created.

Feel free to close this issue if there no questions you'd wanted to ask me
